VideoInsights.Web/Models/DetailsDbViewModel.cs
using VideoInsights.Models;

namespace VideoInsights.Web.Models
{
    public class DetailsDbViewModel
    {
        public Video VideoDetailsData { get; set; }
    }
}

VideoInsights.Web/Models/DetailsViewModel.cs
using VideoInsights.Models;

namespace VideoInsights.Web.Models
{
    public class DetailsViewModel
    {
        public VideoDetailsData VideoDetailsData { get; set; }
        public bool IsNew { get; set; }
    }
}

VideoInsights.Web/Models/ErrorViewModel.cs
using System;

namespace VideoInsights.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VideoInsights.Web/Models/SearchViewModel.cs
using System.Collections.Generic;

using VideoInsights.Models;

namespace VideoInsights.Web.Models
{
    public class SearchViewModel
    {
        public string Text { get; set; }

        public List<VideoData> Videos { get; set; }
    }
}

VideoInsights.Web/Models/UploadViewModel.cs
using Microsoft.AspNetCore.Http;

namespace VideoInsights.Web.Models
{
    public class UploadViewModel
    {
        public IFormFile VideoFile { get; set; }
        public bool Result { get; set; }
    }
}

VideoInsights.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VideoInsights.Web.Models;

namespace VideoInsights.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VideoInsights.Web/Controllers/VideoController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

using VideoInsights.Web.Models;
using VideoInsights.Web.Helpers;
using VideoInsights.Web.Services;

namespace VideoInsights.Web.Controllers
{
    public class VideoController : Controller
    {
        private readonly VideoOptions _options;
        private VideoInsightsApiService _service;

        public VideoController(IOptions<VideoOptions> videoOptions)
        {
            _options = videoOptions.Value;
            _service = new VideoInsightsApiService(_options.Url);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetVideosIndexerData();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var vm = await _service.GetDetails(id);
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsDb(string id)
        {
            var vm = await _service.GetDetailsDb(id);
            return View(vm);
        }

        [HttpGet]
        [ActionName("Upload")]
        public IActionResult UploadView(UploadViewModel vm)
        {
            if (vm == null)
                vm = new UploadViewModel();

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(UploadViewModel vm)
        {
            var vmU = await _service.UploadVideo(vm);
            return UploadView(vmU);
        }


        [HttpPost]
        public async Task<IActionResult> AddDb(string id)
        {
            var vm = await _service.AddDb(id);
            return View("Details", vm);
        }

        [HttpGet]
        public async Task<IActionResult> IndexDb()
        {
            var videos = await _service.GetVideosDb();
            return View(videos);
        }
    }
}

VideoInsights.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

VideoInsights.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoInsights.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VideoInsights.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Index">Videos (index)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="IndexDb">Videos (db)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VideoInsights.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VideoInsights.Web/Views/Video/Details.cshtml
@model VideoInsights.Models.VideoDetailsData

@{
    ViewData["Title"] = "Video Details";
}

<h1>Video Details</h1>

<h3>@Model.Name</h3>

<video controls width="600" height="400">
    <source src="@Model.Uri" type="video/mp4">
    Video tag is not supported in this browser.
</video>

<h3>Frames</h3>

<table class="table">
    <thead>
        <tr>
            <th>Frame</th>
            <th>Start</th>
            <th>End</th>
            <th>Labels</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.KeyFrames)
        {
            <tr>
                <td><img src="@item.Thumbnail.Content" width="300" height="150"></td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeData.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeData.End)
                </td>
                <td>
                    @foreach (var label in item.Labels)
                    {
                        @Html.DisplayFor(modelItem => label.Label)
                        <br/>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

VideoInsights.Web/Views/Video/DetailsDb.cshtml
@model VideoInsights.Web.Models.DetailsDbViewModel

@{
    ViewData["Title"] = "Video Db Details";
}

<h1>Video Details</h1>

<h3>@Model.VideoDetailsData.Name</h3>

<video controls width="600" height="400">
    <source src="@Model.VideoDetailsData.Uri" type="video/mp4">
    Video tag is not supported in this browser.
</video>

<h3>Frames</h3>

<table class="table">
    <thead>
        <tr>
            <th>Frame</th>
            <th>Start</th>
            <th>End</th>
            <th>Labels</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.VideoDetailsData.KeyFrameList)
        {
            <tr>
                <td><img src="@item.Thumbnail.First().Content" width="300" height="150"></td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimePeriod.First().StartTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimePeriod.First().EndTime)
                </td>
                <td>
                    @foreach (var label in item.Labels)
                    {
                        @Html.DisplayFor(modelItem => label.Content)
                        <br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

VideoInsights.Web/Views/Video/Index.cshtml
@model IEnumerable<VideoInsights.Models.VideoData>

@{
    ViewData["Title"] = "Videos from Video Indexer Service";
}

<a asp-action="Upload">Upload Video</a>
<br />
<br />
<h1>Video List</h1>

<table class="table">
    <thead>
        <tr>
            <th>Videos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td align="center">
                    <a asp-action="Details" asp-route-id="@item.Id"><img src="@item.Thumbnail.Content"></a>
                    <br />
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            </tr>
        }
    </tbody>
</table>

VideoInsights.Web/Views/Video/IndexDb.cshtml
@model IEnumerable<VideoInsights.Models.Video>

@{
    ViewData["Title"] = "Videos from Database";
}

<br />
<br />
<h1>Video List</h1>

<table class="table">
    <thead>
        <tr>
            <th>Videos from Database</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td align="center">
                    <a asp-action="DetailsDb" asp-route-id="@item.Id"><img src="@item.Thumbnail.First().Content"></a>
                    <br />
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            </tr>
        }
    </tbody>
</table>

VideoInsights.Web/Views/Video/Search.cshtml
@model VideoInsights.Web.Models.SearchViewModel

@{
    ViewData["Title"] = "Videos from Video Indexer Service";
}

<br />
<br />
<h1>Video Search</h1>
<h4>@Model.Text</h4>

<table class="table">
    <thead>
        <tr>
            <th>Videos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Videos)
        {
            <tr>
                <td align="center">
                    <a asp-action="Details" asp-route-id="@item.Id"><img src="@item.Thumbnail.Content"></a>
                    <br />
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            </tr>
        }
    </tbody>
</table>

VideoInsights.Web/Views/Video/Upload.cshtml
@model VideoInsights.Web.Models.UploadViewModel
@{
    ViewData["Title"] = "Upload Videos to Video Indexer Service";
}

<h1>Upload Video</h1>

<form enctype="multipart/form-data" method="post">
    <dl>
        <dt>
            <label asp-for="VideoFile" />
        </dt>
        <dd>
            <input asp-for="VideoFile" type="file" />
        </dd>
    </dl>
    <input class="btn-primary" type="submit" value="Upload" />
</form>

<br />
<h3>File: @Model.VideoFile?.FileName</h3>

<br />
<h3>Result: @Model.Result</h3>